ARG builder
ARG img

FROM $builder as builder
WORKDIR /build
COPY ./ /build
RUN apk add --no-cache musl-dev
RUN cargo build --release

FROM $img
RUN apk add --no-cache musl-dev
COPY --from=builder /build/target/release/cronized /cronized