name: Check
on:
  push:
    branches:
      - master
  pull_request:
concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true
jobs:
  clippy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Stable with rustfmt and clippy
        uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: stable
          components: rustfmt, clippy
      - name: Rust cache
        uses: Swatinem/rust-cache@v2
      - name: Run tests
        run: cargo clippy

  check-format:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Stable with rustfmt and clippy
        uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: stable
          components: rustfmt, clippy
      - name: Rust cache
        uses: Swatinem/rust-cache@v2
      - name: Run tests
        run: cargo fmt --all -- --check

  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Stable with rustfmt and clippy
        uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: stable
          components: rustfmt, clippy
      - name: Rust cache
        uses: Swatinem/rust-cache@v2
      - name: Run tests
        run: cargo test
