name: Deploy to docker
on:
  push:
    tags:
      - '*'
jobs:
  debian:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        base: [bullseye, slim-bullseye, bookwork, slim-bookworm]
    steps:
      - uses: actions/checkout@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name : Retrieve Version
        run: |
          echo "::set-output name=current-version::$(cat Cargo.toml | grep "^version = \".*\"$" | sed -E 's/version = \"(.+)\"/\1/')"
        id: package-version

      - name: Build and push docker image
        uses: docker/build-push-action@v2
        with:
          context: ./
          file: ./Dockerfile
          builder: ${{ steps.buildx.outputs.name }}
          push: true
          tags: |
            alesharik/cronized:${{ steps.package-version.outputs.current-version }}-${{ matrix.base }}
            alesharik/cronized:${{ matrix.base }}
          build-args: |
            builder=rust:1-${{ matrix.base }}
            img=debian:${{ matrix.base }}

  alpine:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name : Retrieve Version
        run: |
          echo "::set-output name=current-version::$(cat Cargo.toml | grep "^version = \".*\"$" | sed -E 's/version = \"(.+)\"/\1/')"
        id: package-version

      - name: Build and push docker image
        uses: docker/build-push-action@v2
        with:
          context: ./
          file: ./Dockerfile
          builder: ${{ steps.buildx.outputs.name }}
          push: true
          tags: |
            alesharik/cronized:${{ steps.package-version.outputs.current-version }}-alpine3.20
            alesharik/cronized:alpine
          build-args: |
            builder=rust:1-alpine3.20
            img=alpine:3.20